import type { Metadata } from 'next';
import NextTopLoader from 'nextjs-toploader';

import { ApolloProviders } from '@/context/ApolloProvider';
import { SessionProviders } from '@/context/AuthProvider';
import { satoshiFont } from '@/styles/typography.config';

import './globals.css';

export const metadata: Metadata = {
  title: 'Naikyo Proxy HUB',
  description: 'Generated by Naikyo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ApolloProviders>
      <SessionProviders>
        <html lang="en" className={`${satoshiFont.style.fontFamily}`}>
          <link rel="preload" href="/icons/error-help-icon.svg" as="image" />
          <link rel="preload" href="/icons/x-circle.svg" as="image" />
          <body>
            <NextTopLoader color={''} height={2} showSpinner={false} />
            <main>{children}</main>
          </body>
        </html>
      </SessionProviders>
    </ApolloProviders>
  );
}
