import { satoshiFont } from '@/styles/typography.config';
import './globals.css';
import { Metadata } from 'next';
import Header from '@/components/Feature/Layouts/Header';
import Footer from '@/components/Feature/Layouts/Footer';
export const metadata: Metadata = {
  title: 'Naikyo Proxy HUB',
  description: 'Generated by Naikyo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${satoshiFont.style.fontFamily}`}>
      <link rel="preload" href="/icons/error-help-icon.svg" as="image" />
      <link rel="preload" href="/icons/x-circle.svg" as="image" />
      <body className="min-h-screen flex flex-col">
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
