import { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
import ChatWidget from '@/components/Chat/ChatWidget';
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from 'react-hot-toast';

const quicksand = Noto_Sans({
  subsets: ['vietnamese', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-quicksand',
});

export const metadata: Metadata = {
  title: 'Đồ Gia Dụng',
  description: 'Generated by Đồ Gia Dụng',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" className={`${quicksand.variable}`}>
      <body className={`${quicksand.className}`}>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
